version: '3.3'
services:
  db:
    image: 'mysql:latest'
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
        - '3307:3306'
    expose:
      - '3307'
    volumes:
        - mydb:/var/lib/mysql
